lias server="http-server ./"
alias ip="ifconfig en0"
alias vizsh="vi ~/.zshrc"
alias workzsh="source ~/.zshrc"
alias st="git status"
alias ci="git commit -m"
alias ad="git add ."
alias pu="git push origin master"
alias pl="git pull origin master"
alias br="git branch"
alias cl="git clone"
alias df="git diff"
alias cia="git commit --no-edit --amend"
alias ck="git checkout"
alias lg="git log --graph --decorate"

